version: "3.8"
services:
  dev-mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: udemy
      MYSQL_PASSWORD: udemy
      MYSQL_DATABASE: udemy
    restart: always
    networks:
      - lesson
# dev-mysqlはlessonという名前のネットワークに参加しており、lessonに参加しているコンテナ間で通信可能
networks:
  lesson:
