name: backend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
      - name: Run tests
        run: go test -v ./...
      - name: Build
        run: go build -v ./...
