name: backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.backend.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -cover ./... -coverprofile=cover.out
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Go-results-1.20
          path: ./cover.out
          retention-days: 5
